"""empty message

Revision ID: 1af1fb1c355f
Revises: bec789179f73
Create Date: 2021-08-29 07:40:05.112324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af1fb1c355f'
down_revision = 'bec789179f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_buyer_id_fkey', 'transaction', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('transaction_buyer_id_fkey', 'transaction', 'user', ['buyer_id'], ['id'])
    # ### end Alembic commands ###
