"""empty message

Revision ID: 308e6f0e8ea7
Revises: 93a2c680c1ca
Create Date: 2021-08-30 12:40:10.212810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308e6f0e8ea7'
down_revision = '93a2c680c1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('store_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'store_name')
    # ### end Alembic commands ###
