"""empty message

Revision ID: 4f5ad9380857
Revises: d2b0a7b1faa5
Create Date: 2021-09-12 12:57:37.743621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5ad9380857'
down_revision = 'd2b0a7b1faa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdraw_deposit', sa.Column('bank_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdraw_deposit', 'bank_id')
    # ### end Alembic commands ###
