"""empty message

Revision ID: 757ce554612b
Revises: 
Create Date: 2021-08-29 06:22:15.933503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757ce554612b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['id'])
    op.create_unique_constraint(None, 'balance', ['id'])
    op.create_unique_constraint(None, 'transaction', ['id'])
    op.add_column('user', sa.Column('fullnam', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'fullnam')
    op.drop_constraint(None, 'transaction', type_='unique')
    op.drop_constraint(None, 'balance', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
