"""empty message

Revision ID: 8996e7b922e0
Revises: 308e6f0e8ea7
Create Date: 2021-08-30 13:55:07.917672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8996e7b922e0'
down_revision = '308e6f0e8ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'transaction', 'user', ['buyer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    # ### end Alembic commands ###
