"""empty message

Revision ID: 8d85efc66694
Revises: 8996e7b922e0
Create Date: 2021-09-09 18:55:21.725031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d85efc66694'
down_revision = '8996e7b922e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('vendor_comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'vendor_comment')
    # ### end Alembic commands ###
