"""empty message

Revision ID: d2b0a7b1faa5
Revises: 8d85efc66694
Create Date: 2021-09-11 06:26:12.010684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b0a7b1faa5'
down_revision = '8d85efc66694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdraw_deposit', sa.Column('transaction_date', sa.DateTime(), nullable=True))
    op.drop_column('withdraw_deposit', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdraw_deposit', sa.Column('date', sa.VARCHAR(length=11), autoincrement=False, nullable=True))
    op.drop_column('withdraw_deposit', 'transaction_date')
    # ### end Alembic commands ###
